apiVersion: v1
kind: Service
metadata:
  name: nombres
  namespace: api-antonio
spec:
  type: NodePort
  selector:
    app: nombres
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007
  


